apiVersion: v1
kind: Service
metadata:
  name: genymotion
  labels:
    metrics: "genymotion"
    app: "cicd-genymotion"
spec:
  ports:
  - name: 5555-http
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    metrics: genymotion
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}