apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genymotion
  labels:
    metrics: "genymotion"
    app: cicd-genymotion
    version: "3.0.1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi