apiVersion: v1
kind: DeploymentConfig
metadata:
  name: "genymotion"
  labels:
    metrics: "appium"
spec:
  replicas: 1
  selector:
    metrics: "genymotion"
  template:
    metadata:
      labels:
        metrics: "genymotion"
    spec:
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: 500m
          memory: 512Mi
      containers:
      - name: genymotion
        image: "172.30.1.1:5000/appium-server/genymotion:3.0.1"
        ports:
        - containerPort: 5555
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 120
          tcpSocket:
            port: 5555
          timeoutSeconds: 5
        readinessProbe:
          initialDelaySeconds: 180
          tcpSocket:
            port: 5555
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: "/var/lib/genymotion"
          name: "genymotion"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: "genymotion"
        persistentVolumeClaim:
          claimName: "genymotion"
    test: false