apiVersion: v1
kind: BuildConfig
metadata:
  name: "genymotion"
  labels:
    metrics: "genymotion"
    app: "cicd-genymotion"
    version: "3.0.1"
  annotations:
    description: "Builds the MongoDB ebis container."
    template.alpha.openshift.io/wait-for-ready: "true"
resources:
  requests:
    ephemeral-storage: "512Mi"
spec:
  source:
    git:
      uri: "https://github.com/DarrenMun/Appium.git"
      ref: "master"
    # sourceSecret:
      # name: ignore-https-gitconf
    # contextDir: containers/cicd/appium/dockerfile
  strategy:
    dockerStrategy:
      buildargs:
      # - name: NEXUS_ARTIFACT_URL
      #   value: "https://nexus-continuousintegration-dev.app.dev.cpt.ocp.vodacom.corp"
      # - name: NEXUS_ARTIFACT_REPO
      #   value: "thirdparty"
      # - name: NEXUS_GROUP_ID
      #   value: "org/thirdparty/appium"
      # - name: NEXUS_ARTIFACT_ID
      #   value: "appium"
      # - name: NEXUS_ARTIFACT_VERSION
      #   value: "1.7.8"
      # - name: NEXUS_ARTIFACT_CLASSIFIER
      #   value: "1.7.8"
      # - name: NEXUS_ARTIFACT_TYPE
      #   value: "tar.gz"
      # env:
      # - name: PROJECT_NAME
      #   value: "appium"
      # - name: SERVICE_VERSION
      #   value: "1.7.8"
      # - name: SERVICE_DESCRIPTION
      #   value: "appium monitoring"
      # - name: SERVICE_MEMORY
      #   value: "300M"
      # - name: PORT
      #   value: "8888"
      #   protocol: TCP
      dockerfilePath: "Docker_emulator/genymotion.docker"
  output:
    to:
      kind: "ImageStreamTag"
      name: "genymotion:3.0.1"
  triggers:
  - type: "ConfigChange"
  - type: "ImageChange"
    imageChangeParams:
      automatic: true
      containerNames:
      - "genymotion"
      from:
        kind: "ImageStreamTag"
        name: "genymotion:3.0.1"
        namespace: "appium"